openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/cars/:
    get:
      operationId: listCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
          description: ''
      tags:
      - api
  /api/cars-by-user/:
    get:
      operationId: listCars
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
          description: ''
      tags:
      - api
  /api/cars/add/:
    post:
      operationId: createCar
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Car'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
      tags:
      - api
  /api/register/:
    post:
      operationId: createUserRegister
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegister'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegister'
          description: ''
      tags:
      - api
  /api/login/:
    post:
      operationId: createUserLogin
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
          description: ''
      tags:
      - api
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        brand:
          type: string
          maxLength: 20
        model:
          type: string
          maxLength: 20
        year:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        type_car:
          type: string
          maxLength: 20
        transmission:
          enum:
          - M
          - A
          type: string
        price:
          type: number
        user:
          type: integer
      required:
      - brand
      - model
      - year
      - type_car
      - price
      - user
    UserRegister:
      type: object
      properties:
        nombres:
          type: string
          maxLength: 30
        apellidos:
          type: string
          maxLength: 30
        genero:
          type: string
          maxLength: 1
        telefono:
          type: string
          maxLength: 10
        email:
          type: string
          format: email
        password:
          type: string
          maxLength: 20
      required:
      - nombres
      - apellidos
      - genero
      - telefono
      - email
      - password
    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - email
      - password
